//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.23 at 07:12:03 PM MST 
//


package bioportal.beans.response;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{http://bioontology.org/bioportal/classBeanSchema#}fullId" minOccurs="0"/>
 *         &lt;element ref="{http://bioontology.org/bioportal/classBeanSchema#}id" minOccurs="0"/>
 *         &lt;element ref="{http://bioontology.org/bioportal/classBeanSchema#}label" minOccurs="0"/>
 *         &lt;element ref="{http://bioontology.org/bioportal/classBeanSchema#}relations" minOccurs="0"/>
 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fullIdOrIdOrLabel"
})
@XmlRootElement(name = "classBean")
public class ClassBean {

    /*@XmlElementRefs({
        @XmlElementRef(name = "fullId", namespace = "http://bioontology.org/bioportal/classBeanSchema#", type = JAXBElement.class),
        @XmlElementRef(name = "label", namespace = "http://bioontology.org/bioportal/classBeanSchema#", type = JAXBElement.class),
        @XmlElementRef(name = "type", namespace = "http://bioontology.org/bioportal/classBeanSchema#", type = JAXBElement.class),
        @XmlElementRef(name = "relations", namespace = "http://bioontology.org/bioportal/classBeanSchema#", type = Relations.class),
        @XmlElementRef(name = "id", namespace = "http://bioontology.org/bioportal/classBeanSchema#", type = JAXBElement.class)
    })*/
    @XmlElementRefs({
	    @XmlElementRef(name = "fullId", namespace = "", type = JAXBElement.class),
	    @XmlElementRef(name = "label", namespace = "", type = JAXBElement.class),
	    @XmlElementRef(name = "type", namespace = "", type = JAXBElement.class),
	    @XmlElementRef(name = "relations", namespace = "", type = Relations.class),
	    @XmlElementRef(name = "id", namespace = "", type = JAXBElement.class)
    })
    protected List<Object> fullIdOrIdOrLabel;

    /**
     * Gets the value of the fullIdOrIdOrLabel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fullIdOrIdOrLabel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFullIdOrIdOrLabel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link Relations }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<Object> getFullIdOrIdOrLabel() {
        if (fullIdOrIdOrLabel == null) {
            fullIdOrIdOrLabel = new ArrayList<Object>();
        }
        return this.fullIdOrIdOrLabel;
    }

}
