//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.23 at 07:12:03 PM MST 
//


package bioportal.beans.response;

import java.math.BigInteger;
import java.util.ArrayList;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="string" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element ref="{http://bioontology.org/bioportal/classBeanSchema#}list"/>
 *         &lt;/choice>
 *         &lt;element ref="{http://bioontology.org/bioportal/classBeanSchema#}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "stringOrList",
    "_int"
})
@XmlRootElement(name = "entry")
public class Entry {

    @XmlElements({
        @XmlElement(name = "list", type = bioportal.beans.response.List.class),
        @XmlElement(name = "string", type = String.class)
    })
    protected java.util.List<Object> stringOrList;
    @XmlElement(name = "int")
    protected BigInteger _int;

    /**
     * Gets the value of the stringOrList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stringOrList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStringOrList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link beans.response.List }
     * {@link String }
     * 
     * 
     */
    public java.util.List<Object> getStringOrList() {
        if (stringOrList == null) {
            stringOrList = new ArrayList<Object>();
        }
        return this.stringOrList;
    }

    /**
     * Gets the value of the int property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getInt() {
        return _int;
    }

    /**
     * Sets the value of the int property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setInt(BigInteger value) {
        this._int = value;
    }

}
