//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.23 at 07:12:03 PM MST 
//


package bioportal.beans.response;

import java.util.ArrayList;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element ref="{http://bioontology.org/bioportal/classBeanSchema#}classBean" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element name="string" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "classBeanOrString"
})
@XmlRootElement(name = "list")
public class List {

    @XmlElements({
        @XmlElement(name = "classBean", type = ClassBean.class),
        @XmlElement(name = "string", type = String.class)
    })
    protected java.util.List<Object> classBeanOrString;

    /**
     * Gets the value of the classBeanOrString property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the classBeanOrString property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getClassBeanOrString().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ClassBean }
     * {@link String }
     * 
     * 
     */
    public java.util.List<Object> getClassBeanOrString() {
        if (classBeanOrString == null) {
            classBeanOrString = new ArrayList<Object>();
        }
        return this.classBeanOrString;
    }

}
