//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.23 at 07:12:03 PM MST 
//


package bioportal.beans.response;

import java.math.BigInteger;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the beans package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	/*
    private final static QName _AccessDate_QNAME = new QName("http://bioontology.org/bioportal/classBeanSchema#", "accessDate");
    private final static QName _Label_QNAME = new QName("http://bioontology.org/bioportal/classBeanSchema#", "label");
    private final static QName _FullId_QNAME = new QName("http://bioontology.org/bioportal/classBeanSchema#", "fullId");
    private final static QName _Id_QNAME = new QName("http://bioontology.org/bioportal/classBeanSchema#", "id");
    private final static QName _AccessedResource_QNAME = new QName("http://bioontology.org/bioportal/classBeanSchema#", "accessedResource");
    private final static QName _Int_QNAME = new QName("http://bioontology.org/bioportal/classBeanSchema#", "int");
    private final static QName _ClassBeanType_QNAME = new QName("http://bioontology.org/bioportal/classBeanSchema#", "type");
	*/
	private final static QName _AccessDate_QNAME = new QName("accessDate");
    private final static QName _Label_QNAME = new QName("label");
    private final static QName _FullId_QNAME = new QName("fullId");
    private final static QName _Id_QNAME = new QName("id");
    private final static QName _AccessedResource_QNAME = new QName("accessedResource");
    private final static QName _Int_QNAME = new QName("int");
    private final static QName _ClassBeanType_QNAME = new QName("type");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: beans
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Data }
     * 
     */
    public Data createData() {
        return new Data();
    }

    /**
     * Create an instance of {@link List }
     * 
     */
    public List createList() {
        return new List();
    }

    /**
     * Create an instance of {@link ClassBean }
     * 
     */
    public ClassBean createClassBean() {
        return new ClassBean();
    }

    /**
     * Create an instance of {@link Entry }
     * 
     */
    public Entry createEntry() {
        return new Entry();
    }

    /**
     * Create an instance of {@link Success }
     * 
     */
    public Success createSuccess() {
        return new Success();
    }

    /**
     * Create an instance of {@link Relations }
     * 
     */
    public Relations createRelations() {
        return new Relations();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    //@XmlElementDecl(namespace = "http://bioontology.org/bioportal/classBeanSchema#", name = "accessDate")
    @XmlElementDecl(namespace = "", name = "accessDate")
    public JAXBElement<String> createAccessDate(String value) {
        return new JAXBElement<String>(_AccessDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    //@XmlElementDecl(namespace = "http://bioontology.org/bioportal/classBeanSchema#", name = "label")
    @XmlElementDecl(namespace = "", name = "label")
    public JAXBElement<String> createLabel(String value) {
        return new JAXBElement<String>(_Label_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    //@XmlElementDecl(namespace = "http://bioontology.org/bioportal/classBeanSchema#", name = "fullId")
    @XmlElementDecl(namespace = "", name = "fullId")
    public JAXBElement<String> createFullId(String value) {
        return new JAXBElement<String>(_FullId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    //@XmlElementDecl(namespace = "http://bioontology.org/bioportal/classBeanSchema#", name = "id")
    @XmlElementDecl(namespace = "", name = "id")
    public JAXBElement<String> createId(String value) {
        return new JAXBElement<String>(_Id_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    //@XmlElementDecl(namespace = "http://bioontology.org/bioportal/classBeanSchema#", name = "accessedResource")
    @XmlElementDecl(namespace = "", name = "accessedResource")
    public JAXBElement<String> createAccessedResource(String value) {
        return new JAXBElement<String>(_AccessedResource_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    //@XmlElementDecl(namespace = "http://bioontology.org/bioportal/classBeanSchema#", name = "int")
    @XmlElementDecl(namespace = "", name = "int")
    public JAXBElement<BigInteger> createInt(BigInteger value) {
        return new JAXBElement<BigInteger>(_Int_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    //@XmlElementDecl(namespace = "http://bioontology.org/bioportal/classBeanSchema#", name = "type", scope = ClassBean.class)
    @XmlElementDecl(namespace = "", name = "type", scope = ClassBean.class)
    public JAXBElement<String> createClassBeanType(String value) {
        return new JAXBElement<String>(_ClassBeanType_QNAME, String.class, ClassBean.class, value);
    }

}
