//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.23 at 07:12:03 PM MST 
//

//@javax.xml.bind.annotation.XmlSchema(namespace = "http://bioontology.org/bioportal/classBeanSchema#", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package bioportal.beans.response;
